ALTER TABLE xxnbty.xxnbty_pegging_temp_tbl
ADD(
     ORDER_PRIORITY_RM         NUMBER
    ,ORDER_PRIORITY_BL         NUMBER
    ,ORDER_PRIORITY_BC         NUMBER
    ,ORDER_PRIORITY_FG         NUMBER
    ,ORDER_PRIORITY_DD         NUMBER
    ,SOURCE_ORDER_PRIORITY_FG  NUMBER
    ,SOURCE_ORDER_PRIORITY_DD  NUMBER
);
